version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - mysql_container:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3308:3308
    environment:

       MYSQL_DATABASE: 'achat-db'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: oumad/achat-1.1:78
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app
    environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3308/tpachato?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
    

volumes:
  mysql_container: { }
