version: '3.3'
services:
  mysqldb:
    container_name: mysqldb1
    image: mysql:latest
    volumes:
      - mysql_container:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3306:3306
    environment:

       MYSQL_DATABASE: 'achat-db'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
   sonarqube:
      image: sonarqube:8.9.7-community
      ports:
      - "9000:9000"
       volumes:
         - 'SonarQube_data:/opt/SonarQube/data'
         - 'SonarQube_extensions:/opt/SonarQube/extensions'
       - 'SonarQube_logs:/opt/SonarQube/logs'
    nexus:
        image: sonatype/nexus3
        ports:
         - "8081:8081"
        volumes:
         - 'nexus-data:/nexus-data'


  spring_app:
    depends_on:
      - mysqldb
    image: oumad/achat-1.1:78
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app

volumes:
  mysql_container: { }
